"""rate limit indexes and display_name length cap

Revision ID: 18f2d7735523
Revises: ef8394b37c8d
Create Date: 2026-08-11 13:52:11.362735

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18f2d7735523"
down_revision: str | None = "ef8394b37c8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Raw DDL (rather than op.alter_column) so the truncation of any
    # existing display_name longer than 255 chars is atomic with the type
    # change — a plain TEXT->VARCHAR(255) ALTER aborts mid-migration on
    # PostgreSQL if any row violates the new length, leaving the schema
    # partially migrated (DDL auto-commits) and crashlooping the container.
    op.execute(
        "ALTER TABLE agents ALTER COLUMN display_name "
        "TYPE varchar(255) USING left(display_name, 255)"
    )
    op.create_index(
        "idx_conversations_created_by_created_at",
        "conversations",
        ["created_by", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_messages_conversation_id_sender_id_created_at",
        "messages",
        ["conversation_id", "sender_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_conversation_id_sender_id_created_at", table_name="messages")
    op.drop_index("idx_conversations_created_by_created_at", table_name="conversations")
    op.alter_column(
        "agents",
        "display_name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
