"""rate limit indexes and display_name length cap

Revision ID: 18f2d7735523
Revises: ef8394b37c8d
Create Date: 2026-08-11 13:52:11.362735

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18f2d7735523"
down_revision: str | None = "ef8394b37c8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Surface how many rows (if any) will be truncated by the ALTER below,
    # since that truncation is silent and irreversible (downgrade() cannot
    # recover the lost characters — see note there).
    op.execute(
        sa.text(
            "DO $$ DECLARE n int; BEGIN "
            "SELECT count(*) INTO n FROM agents WHERE length(display_name) > 255; "
            "IF n > 0 THEN "
            "RAISE NOTICE '% agent row(s) will have display_name truncated to 255 chars', n; "
            "END IF; END $$;"
        )
    )
    # Raw DDL (rather than op.alter_column) with an explicit USING clause:
    # PostgreSQL DDL is fully transactional, so on its own a plain
    # TEXT->VARCHAR(255) ALTER wouldn't leave a "partially migrated" schema —
    # it would just abort and roll back the entire migration transaction if
    # any existing row exceeds 255 chars. USING truncates proactively so the
    # migration succeeds instead of aborting. This is acceptable because
    # service.py enforces the 255-char cap at the application layer as of
    # this revision, so any truncation here only affects rows written before
    # that enforcement existed.
    op.execute(
        "ALTER TABLE agents ALTER COLUMN display_name "
        "TYPE varchar(255) USING left(display_name, 255)"
    )
    op.create_index(
        "idx_conversations_created_by_created_at",
        "conversations",
        ["created_by", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "idx_messages_conversation_id_sender_id_created_at",
        "messages",
        ["conversation_id", "sender_id", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    # DB-level backstop for schemas.MAX_ACCEPTED_TYPES (currently 20) so a
    # write that bypasses the service-layer validator (raw SQL, a future
    # data-fix migration, etc.) can't silently store an oversized array.
    # Hardcoded rather than imported from application code — migrations are
    # frozen snapshots of DDL, not consumers of app modules — so keep this
    # literal in sync with schemas.MAX_ACCEPTED_TYPES if that value changes.
    op.create_check_constraint(
        "ck_agents_accepted_types_max",
        "agents",
        "array_length(accepted_types, 1) <= 20",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_agents_accepted_types_max", "agents")
    op.drop_index("idx_messages_conversation_id_sender_id_created_at", table_name="messages")
    op.drop_index("idx_conversations_created_by_created_at", table_name="conversations")
    # Lossy: any display_name that was truncated to 255 chars during
    # upgrade() cannot be restored to its original length — this only
    # reverses the column type, not the data.
    op.alter_column(
        "agents",
        "display_name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
