"""rate limit indexes and display_name length cap

Revision ID: 18f2d7735523
Revises: ef8394b37c8d
Create Date: 2026-08-11 13:52:11.362735

NOTE on in-place amendment: this revision was authored and iterated on
entirely within this single unmerged PR (agent-comms-mcp PR #1) -- it does
not exist on `main`, and it has never been applied to any persistent or
shared database (no deployed environment for this service exists yet; CI
runs `alembic upgrade head` against a fresh, ephemeral Postgres service
container on every run; local review testing always ran full
`downgrade base` -> `upgrade head` cycles against the latest file content).
In-place amendment during code review was therefore safe. Once this PR
merges, treat this file as frozen: any further schema change requires a
NEW Alembic revision, never an edit to this one.

"""

from __future__ import annotations

import logging
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op

# revision identifiers, used by Alembic.
revision: str = "18f2d7735523"
down_revision: str | None = "ef8394b37c8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

logger = logging.getLogger("alembic.runtime.migration")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Surface how many rows (if any) will be truncated by the ALTER below,
    # since that truncation is silent and irreversible (downgrade() cannot
    # recover the lost characters -- see note there). A Postgres `RAISE
    # NOTICE` won't do here: asyncpg (this repo's async driver) silently
    # discards server NOTICE messages by default, so nothing would ever
    # surface it. Instead, do the count in Python and log it, which lands
    # in Alembic's own stdout/stderr output.
    #
    # Skipped in offline mode (e.g. `alembic upgrade head --sql`): there is
    # no live connection to query in that mode, so the count can't be known
    # and the warning below is skipped along with it.
    if not context.is_offline_mode():
        bind = op.get_context().connection
        if bind is None:
            # Guaranteed non-None by the is_offline_mode() check above; an
            # `assert` here would be stripped under `python -O`, silently
            # turning this into a less diagnostic AttributeError below.
            raise RuntimeError("Expected a live DB connection in online Alembic context")
        truncated_count = bind.execute(
            sa.text("SELECT count(*) FROM agents WHERE length(display_name) > 255")
        ).scalar()
        if truncated_count:
            logger.warning(
                "%s agent row(s) will have display_name truncated to 255 chars", truncated_count
            )
    # Raw DDL (rather than op.alter_column) with an explicit USING clause:
    # PostgreSQL DDL is fully transactional, so on its own a plain
    # TEXT->VARCHAR(255) ALTER wouldn't leave a "partially migrated" schema --
    # it would just abort and roll back the entire migration transaction if
    # any existing row exceeds 255 chars. USING truncates proactively so the
    # migration succeeds instead of aborting. This is acceptable because
    # service.py enforces the 255-char cap at the application layer as of
    # this revision, so any truncation here only affects rows written before
    # that enforcement existed.
    op.execute(
        "ALTER TABLE agents ALTER COLUMN display_name "
        "TYPE varchar(255) USING left(display_name, 255)"
    )
    op.create_index(
        "idx_conversations_created_by_created_at",
        "conversations",
        ["created_by", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "idx_messages_conversation_id_sender_id_created_at",
        "messages",
        ["conversation_id", "sender_id", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    # DB-level backstop for schemas.MAX_ACCEPTED_TYPES (currently 20) so a
    # write that bypasses the service-layer validator (raw SQL, a future
    # data-fix migration, etc.) can't silently store an oversized array.
    # Hardcoded rather than imported from application code -- migrations are
    # frozen snapshots of DDL, not consumers of app modules -- so keep this
    # literal in sync with schemas.MAX_ACCEPTED_TYPES if that value changes.
    # cardinality() (not array_length()) so an empty array yields 0, never
    # NULL -- a NULL CHECK expression is treated as satisfied by Postgres,
    # which would make this constraint silently unable to reject anything
    # for the empty-array edge case.
    op.create_check_constraint(
        "ck_agents_accepted_types_max",
        "agents",
        "cardinality(accepted_types) <= 20",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_agents_accepted_types_max", "agents", type_="check")
    op.drop_index("idx_messages_conversation_id_sender_id_created_at", table_name="messages")
    op.drop_index("idx_conversations_created_by_created_at", table_name="conversations")
    # Lossy: any display_name that was truncated to 255 chars during
    # upgrade() cannot be restored to its original length -- this only
    # reverses the column type, not the data.
    op.alter_column(
        "agents",
        "display_name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
